obstacle_range: 15.0
raytrace_range: 5.0
footprint: [[.36, .25], [.36, -0.25], [-0.29, -0.25], [-0.29, .25]]
#robot_radius: ir_of_robot
inflation_radius: 0.30

# settings for simulation
#observation_sources: base_scan

#base_scan: {sensor_frame: base_laser_link, data_type: LaserScan, topic: base_scan, marking: true, clearing: true}

# settings for real robot
observation_sources: rplidar

rplidar: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
