obstacle_range: 15.0
raytrace_range: 15.0
footprint: [[.36, .25], [.36, -0.25], [-0.29, -0.25], [-0.29, .25]]
#robot_radius: ir_of_robot
inflation_radius: 0.30

plugins:
  - {name: obstacles,   type: "costmap_2d::VoxelLayer"} # laser scans
  - {name: static_map,  type: "costmap_2d::StaticLayer"} # bitmap
  - {name: inflation,  type: "costmap_2d::InflationLayer"} # size of robot
  - {name: social_layer, type: "social_navigation_layers::ProxemicLayer"} # leg detection

inflation:
  inflation_radius: 0.3

obstacles:
  observation_sources: scan
  scan: {data_type: LaserScan, sensor_frame: laser, clearing: true, marking: true, topic: scan}
