global_frame: map
robot_base_frame: base_link

plugins:
  - {name: static_map,  type: "costmap_2d::StaticLayer"}
  - {name: inflation,  type: "costmap_2d::InflationLayer"} # size of robot

inflation:
  inflation_radius: 0.3
