plugins:
  - {name: static,  type: "costmap_2d::StaticLayer"}
  - {name: inflation,  type: "costmap_2d::InflationLayer"} # size of robot

footprint: [[.36, .25], [.36, -0.25], [-0.29, -0.25], [-0.29, .25]]

global_frame: map
robot_base_frame: base_link
transform_tolerance: 0.2
update_frequency: 5.0
publish_frequency: 0.0
rolling_window: false
always_send_full_costmap: false
width: 10
height: 10
resolution: 0.05
origin_x: 0.0
origin_y: 0.0

static:
  unknown_cost_value: -1
  lethal_cost_threshold: 100
  map_topic: map
  first_map_only: false
  subscribe_to_updates: false
  track_unknown_space: true
  use_maximum: false
  trinary_costmap: true

inflation:
  inflation_radius: 0.3
  cost_scaling_factor: 10.0
