plugins:
  - {name: obstacles, type: "costmap_2d::VoxelLayer"} # laser scans
  - {name: inflation,  type: "costmap_2d::InflationLayer"} # size of robot
  - {name: social, type: "social_navigation_layers::ProxemicLayer"} # people detection
  - {name: passing, type: "social_navigation_layers::PassingLayer"} # people detection

footprint: [[.36, .25], [.36, -0.25], [-0.29, -0.25], [-0.29, .25]]

global_frame: map
robot_base_frame: base_link
transform_tolerance: 0.2
update_frequency: 5.0
publish_frequency: 1.0
rolling_window: true
always_send_full_costmap: false
width: 10
height: 10
resolution: 0.05
origin_x: 0.0
origin_y: 0.0

obstacles:
  observation_sources: scan
  scan:
    {
    topic: scan,
    sensor_frame: laser,
    observation_persistence: 0.0,
    expected_update_rate: 0.0,
    data_type: LaserScan,
    clearing: true,
    marking: true,
    max_obstacle_height: 2.0,
    min_obstacle_height: 0.0,
    obstacle_range: 15.0,
    raytrace_range: 5.0
    }
  track_unknown_space: false
  footprint_clearing_enabled: true
  combination_method: 1
  origin_z: 0.0
  z_resolution: 0.2
  z_voxels: 10
  unknown_threshold: 10
  mark_threshold: 0
  publish_voxel_map: false
  footprint_clearing_enabled: true

inflation:
  inflation_radius: 0.3
  cost_scaling_factor: 10.0

#social:
#  enabled: true
#  cutoff: 10.0
#  amplitude: 77.0
#  covariance: 0.25
#  factor: 5.0
#  keep_time: 0.75

#passing:
#  enabled: true
#  cutoff: 10.0
#  amplitude: 77.0
#  covariance: 0.25
#  factor: 5.0
#  keep_time: 0.75
